package de.zebrajaeger.phserver.record;

public enum States {
    RUNNING, STOPPED,

    STARTING, IDLE,

    EXEC_MOVE, EXEC_MOVE_STOP, EXEC_MOVE_PAUSE_RUNNING, EXEC_MOVE_PAUSE_IDLE,
    EXEC_DELAY, EXEC_DELAY_STOP, EXEC_DELAY_PAUSE_RUNNING, EXEC_DELAY_PAUSE_IDLE,
    EXEC_SHOT, EXEC_SHOT_STOP, EXEC_SHOT_PAUSE_RUNNING, EXEC_SHOT_PAUSE_IDLE,
    EXEC_APPLY_OFFSET, EXEC_APPLY_OFFSET_STOP,
    EXEC_NORMALIZE_POSITION, EXEC_NORMALIZE_POSITION_STOP,

    STOPPED_SUCCESSFULLY, STOPPED_WITH_ERROR,

    WRITE_PAPYWIZARD
}
