spring.profiles.default=target

# Server
http.port=8080
server.address=0.0.0.0

# SSL
server.port=8443
server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=selfsigned
server.ssl.key-store=classpath:server-java.p12
server.ssl.key-alias=server
server.ssl.key-store-password=geheim

# MQTT
# Target first, local Server second
mqtt.server.url=tcp://192.168.1.205:1883

# I2C
i2c.address.panohead=0x33
i2c.remote.host=192.168.178.78:8079

# Config files
settings.autosave.delay=2

# Actuator
#management.endpoints.web.exposure.include=*
#endpoints.beansviz.enabled=true

# Logging
logging.file.path=.
logging.file.name=ph.log
logging.level.de.zebrajaeger.phserver.service.RobotService=DEBUG
logging.level.net.java.games.input.ControllerEnvironment=WARN

# Software info
project.version=@project.version@
#project.timestamp=@timestamp@

# System paths
system.media.root=/media/pi

# ------------------
# DEVELOP profile
# ------------------
develop.updatesPerSecond=5

# Components
enable.ph.version=v5

enable.mqtt=true
enable.i2c.local=false
enable.i2c.remote=false

enable.actor.fake=false
enable.actor.mqtt=true
enable.actor.mqtt.status=false
enable.actor.i2c=false
enable.actor.udp.status=true

enable.accelerationsensor.adxl345=false

enable.camera.fake=false
enable.camera.ccapi=true
enable.camera.i2c=false
enable.camera.mqtt=false

enable.gps.i2c=false
enable.gps.fake=false

enable.joystick.usb=false
enable.joystick.i2c=false

enable.powergauge.i2c.ina219=false
enable.powergauge.fake=false

enable.syscontrol.fake=false
enable.syscontrol.linux=true