server.ssl.key-store=classpath:pcw-java.p12
server.ssl.key-alias=pcw
server.ssl.key-store-password=geheim

spring.main.banner-mode=off

# Components
enable.camera.fake=true
enable.camera.ccapi=false
enable.syscontrol.fake=true
enable.syscontrol.linux=false

#logging.level.org.springframework.statemachine = DEBUG
#logging.level.de.zebrajaeger.phserver.service.RobotService=DEBUG
logging.level.net.java.games.input.ControllerEnvironment=WARN
#logging.level.org.springframework.web.socket.config.WebSocketMessageBrokerStats = DEBUG
#logging.level.org.springframework.web.socket = TRACE

