# default profiles
spring.profiles.default=v5, mqtt-actor, ccapi-cam, linux-sysctrl

# Server
http.port=8080
server.address=0.0.0.0

# SSL
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=selfsigned

# MQTT
# Target first, local Server second
mqtt.server.url=tcp://192.168.178.78:1883,tcp://192.168.178.42:1883

# I2C
i2c.address.panohead=0x33
i2c.remote.host=192.168.178.78:8079

# Config files
settings.autosave.delay=2

# Actuator
#management.endpoints.web.exposure.include=*
#endpoints.beansviz.enabled=true

# Logging
logging.file.path=.
logging.file.name=ph.log
logging.level.de.zebrajaeger.phserver.service.RobotService=DEBUG
logging.level.net.java.games.input.ControllerEnvironment=WARN

# Software info
project.version=@project.version@
#project.timestamp=@timestamp@

# System paths
system.media.root=/media/pi

# ------------------
# DEVELOP profile
# ------------------
develop.updatesPerSecond=5
