server.ssl.key-store=classpath:pcw-java.p12
server.ssl.key-alias=pcw
server.ssl.key-store-password=geheim

spring.main.banner-mode=off

# Components
enable.camera.fake=true
enable.camera.ccapi=false
enable.syscontrol.fake=true
enable.syscontrol.linux=false