spring.profiles.default=mqtt,v5,ccapi

http.port=8080
server.address=0.0.0.0
i2c.address.panohead=0x33
#
i2c.remote.host=192.168.178.78:8079
settings.autosave.delay=2
logging.level.de.zebrajaeger.phserver.service.RobotService=DEBUG
logging.level.net.java.games.input.ControllerEnvironment=WARN

management.endpoints.web.exposure.include=*
endpoints.beansviz.enabled=true

logging.file.path=.
logging.file.name=ph.log
#
# DEVELOP profile
#
develop.updatesPerSecond=5

# Build
project.version=@project.version@
#project.timestamp=@timestamp@

system.media.root=/media/pi

# SSL stuff
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=selfsigned